services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/pedido
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_RABBITMQ_HOST=rabbitmq # ou configure no application.properties/yml
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=fiap
      - SPRING_RABBITMQ_PASSWORD=fiap
    networks:
      - springboot-postgres-network
      - springboot-rabbitmq-network

  postgresql:
    image: postgres:15-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=pedido
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - springboot-postgres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      retries: 10
      interval: 10s
      timeout: 5s

volumes:
  postgres-data:

networks:
  springboot-postgres-network:
    name: fiap-network
  springboot-rabbitmq-network:
    name: fiap-rabbitmq-network
